name: TopMineLeaderboard
api: [5.0.0]
version: 2.0.0
author: reyyoga & AlvinHere
main: reyyoga\Main

commands:
 settopmine:
     description: "set leaderboard location"
     permission: "settopmine.lb"
permissions:
  settopmine.lb:
    description: "topmineleaderboard command permission!"
    default: op
